### PR TITLE
Redesigned IIITA website

### PR DESCRIPTION
**Pull request by shlesh**
Issue: 263

#### Short description of what this resolves:

shlesh

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by shlesh** [comment]
@zorione maam can you please review my PR

**Comment by shlesh** [comment]
@zorione maam🥺🥺🥺

**Comment by zorione** [comment]
> @zorione maam🥺🥺🥺

Give me some time. hardly any changes are required, I have seen the site. I will let you know soon.

**Comment by shlesh** [comment]
> 
> 
> > @zorione maam🥺🥺🥺
> 
> Give me some time. hardly any changes are required, I have seen the site. I will let you know soon.

Right maam, thank you soo much!!!

**Comment by zorione** [comment]
@shlesh join vc at 6 today. Will tell you the changes.

**Comment by shlesh** [comment]
> @shlesh join vc at 6 today. Will tell you the changes. 

Oka thank you maam!! Will be there

**Comment by zorione** [comment]
Amazing work dude!!!

**Comment by shlesh** [comment]
> 
> 
> Amazing work dude!!!

Thank you soo much maam!!!

**Pull request merged**
