### PR TITLE
Added design

### PR DESCRIPTION
**Pull request by schandu-eng**
Issue: 263

Bright

### CODE REVIEW

**Comment by ShreyaShrotriya** [comment]
@schandu-eng except for the logo in the top left corner, the site isn't looking like that of IIITA that too an official website, please make changes accordingly.

**Comment by zorione** [comment]
Change the illustration on top

**Comment by schandu-eng** [comment]
@zorione ma'am the screen shot was of the older one
Now I have changed it (as presented to you around 3-4 pm)

**Comment by schandu-eng** [comment]
@zorione ma'am 🙄

**Pull request merged**
