### PR TITLE
Iiita redesign

### PR DESCRIPTION
**Pull request by Dheeraj096**
Issue: 263

#### Short description of what this resolves:
Redesign IIITA

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by zorione** [comment]
It requires changes. Join the discord and tag me, I will join @Dheeraj096

**Comment by Dheeraj096** [comment]
@zorione  please check i made more few changes also.

**Comment by Manav1410** [comment]
It requires changes. Join the discord and tag us.

**Comment by Dheeraj096** [comment]
made more changes @karrocks @Manav1410 @zorione is it fine now?

**Comment by ShreyaShrotriya** [comment]
@Dheeraj096 the cards are not looking good, try not to use images as background when there is text and also give some padding.

**Comment by Dheeraj096** [comment]
now? @ShreyaShrotriya

**Comment by zorione** [comment]
Great work @Dheeraj096 👍

**Pull request merged**
